#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Proxy setup — Anonymous free-tier via Operator Key
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "ASM Agent — Proxy setup (Anonymous Free Models)"

# ── Stage 1: Cloudflare login ─────────────────────────────────────────────
stage "Cloudflare: log in Wrangler"
say "The Proxy is a Cloudflare Worker. Wrangler must be logged in to store the Operator Key."
say "Current status:"
npx wrangler whoami 2>&1 | sed 's/^/  /' || true
echo
if npx wrangler whoami >/dev/null 2>&1; then
  note "Already logged in — press Enter to keep going."
  pause "Continue"
else
  step "Run 'npx wrangler login' — it will open a browser to Cloudflare."
  note "Press Enter to open the login now."
  pause "Open browser"
  npx wrangler login || true
  echo
  say "Checking again..."
  npx wrangler whoami 2>&1 | sed 's/^/  /' || warn "Login still not OK — you can finish login later and re-run this wizard."
  pause "Continue when logged in"
fi

# ── Stage 2: Operator Key ─────────────────────────────────────────────────
stage "OpenRouter: Operator Key"
say "Free Model (:free) still needs a key. The Proxy holds it server-side for Anonymous Users."
open_url "https://openrouter.ai/keys"
step "On openrouter.ai/keys, click 'Create API Key' (name it e.g. asm-proxy)."
step "Copy the key (starts sk-or-...). It will only be shown once."
ask_secret OPENROUTER_KEY "Paste the Operator Key (sk-or-...):"
# keep a local copy for re-runs, but the real secret lives in Cloudflare
write_env OPENROUTER_KEY "$OPENROUTER_KEY"
say "Storing key in Cloudflare Worker as secret OPENROUTER_KEY..."
if printf '%s' "$OPENROUTER_KEY" | npx wrangler secret put OPENROUTER_KEY 2>&1 | sed 's/^/  /'; then
  note "Secret stored."
else
  warn "Could not store secret. Try by hand:"
  note "  printf '%s' \"\$OPENROUTER_KEY\" | npx wrangler secret put OPENROUTER_KEY"
  SKIPPED+=("npx wrangler secret put OPENROUTER_KEY")
fi
note "For BYO Users, nothing changes — they still paste their own key in SET."

# ── Stage 3: Deploy + verify ──────────────────────────────────────────────
stage "Deploy Proxy and verify"
say "Deploying Worker 'asm-agent-proxy' (wrangler.toml)..."
if npx wrangler deploy 2>&1 | sed 's/^/  /'; then
  note "Deployed."
else
  warn "Deploy failed — check 'npx wrangler deploy' output."
  SKIPPED+=("npx wrangler deploy")
fi

say "Verify health endpoint (replace with your Worker URL if you use a custom route):"
note "  curl -s https://asm-agent-proxy.<your-subdomain>.workers.dev/api/health | jq"
note "Expected: {\"ok\":true,\"freeOnly\":true}"
echo
say "Local quick check — Proxy must 403 paid models without key:"
note "  curl -s -X POST http://localhost:8000/api/chat -H 'content-type: application/json' -d '{\"model\":\"openai/gpt-4o\",\"messages\":[]}' | jq"
note "Expected: 403 NOT_FREE"
echo
confirm "Did the deploy and health check look OK?" || warn "Re-run this wizard after fixing."

finish
